import sys
integer=int(input("enter a number:"))
print("value: ",integer)
print("type: ", type(integer))
print(sys.getsizeof(integer))
floatt=float(input("enter a float variable: "))
print("value: ",floatt)
print("type: ", type(floatt))
print(sys.getsizeof(floatt))
comp=complex(input("enter a complex number:"))
print("value: ",comp)
print("type: ", type(comp))
print(sys.getsizeof(comp))
print(comp.real," ",comp.imag," ",abs(comp))
boolean=bool(input("enter a boolean value:"))
print("value: ",boolean)
print("type: ", type(boolean))
print(sys.getsizeof(boolean))
boolean1=bool(input("enter 1st boolean value:"))
boolean2=bool(input("enter 2nd boolean value:"))
print(boolean1 and boolean2)
print(boolean1 or boolean2)
print(not boolean1)
print(not boolean2)
string=str(input("enter a string:"))
print("value: ",string)
print("type: ", type(string))
print(sys.getsizeof(string))
print(float(integer))
print(int(floatt))
print(str(integer))
string2=input("enter a number:")
print(int(string2))
print(int(boolean))
print(complex(integer))